import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const isConfigured = Boolean(supabaseUrl && supabaseAnonKey && supabaseUrl !== 'https://your-project.supabase.co');

export const supabase = createClient(
  supabaseUrl || 'https://placeholder.supabase.co', 
  supabaseAnonKey || 'placeholder'
);

/**
 * DATABASE SCHEMA REFERENCE (As per requirements)
 * 
 * -- Employees Table
 * CREATE TABLE employees (
 *   id TEXT PRIMARY KEY,
 *   full_name TEXT NOT NULL,
 *   mobile TEXT,
 *   group_name TEXT REFERENCES groups(name),
 *   doj DATE,
 *   status TEXT DEFAULT 'Active' -- 'Active', 'Removed', 'Inactive'
 * );
 * 
 * -- Petrol Logs Table
 * CREATE TABLE petrol_logs (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   vehicle_id TEXT NOT NULL,
 *   total_given DECIMAL NOT NULL,
 *   remaining DECIMAL NOT NULL,
 *   consumption DECIMAL GENERATED ALWAYS AS (total_given - remaining) STORED,
 *   date DATE DEFAULT CURRENT_DATE
 * );
 * 
 * -- Attendance Table
 * CREATE TABLE attendance (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   employee_id TEXT REFERENCES employees(id),
 *   check_in TIMESTAMP WITH TIME ZONE,
 *   check_out TIMESTAMP WITH TIME ZONE,
 *   working_hours DECIMAL,
 *   leave_status BOOLEAN DEFAULT FALSE,
 *   date DATE DEFAULT CURRENT_DATE
 * );
 * 
 * -- Clients Table
 * CREATE TABLE clients (
 *   id TEXT PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   place TEXT,
 *   timing TEXT,
 *   assigned_employee_id TEXT REFERENCES employees(id),
 *   status TEXT DEFAULT 'Active'
 * );
 * 
 * -- Advances Table
 * CREATE TABLE advances (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   employee_id TEXT REFERENCES employees(id),
 *   amount DECIMAL NOT NULL,
 *   reason TEXT,
 *   date DATE DEFAULT CURRENT_DATE
 * );
 * 
 * -- Groups Table
 * CREATE TABLE groups (
 *   name TEXT PRIMARY KEY,
 *   description TEXT
 * );
 */
